# Lists

In [1]:
aList = ["John", 33,"Toronto", True]

In [2]:
aList

['John', 33, 'Toronto', True]

In [3]:
type(aList)

list

In [4]:
bin_colors=['Red','Green','Blue','Yellow']

# Tuples

In [5]:
bin_colors=('Red','Green','Blue','Yellow')
print(f"The second element of the tuple is {bin_colors[1]}")

The second element of the tuple is Green


In [6]:
print(f"The elements after third element onwards are {bin_colors[2:]}")

The elements after third element onwards are ('Blue', 'Yellow')


In [7]:
nested_tuple = (1,2,(100,200,300),6)
print(f"The maximum value of the inner tuple {max(nested_tuple[2])}")

The maximum value of the inner tuple 300


# Dictionary

In [8]:
bin_colors ={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

In [9]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [10]:
bin_colors.get('approved_color')

'Green'

In [11]:
bin_colors['approved_color']="Purple"

In [12]:
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


# Sets

In [13]:
green = {'grass', 'leaves'}
print(green)

{'leaves', 'grass'}


In [14]:
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}

In [15]:
print(f"The union of yellow and red sets is{yellow|red}")

The union of yellow and red sets is{'rose', 'fire hydrant', 'dandelions', 'blood', 'leaves'}


In [16]:
print(f"The intersaction of yellow and red is {yellow&red}")

The intersaction of yellow and red is {'leaves', 'fire hydrant'}


# Data Frames

In [17]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True


In [18]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [19]:
df.iloc[:,]

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [20]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [21]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

# Matrix

In [22]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])

In [23]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [24]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [25]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

# Vector

In [26]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [27]:
print(type(myVector))

<class 'list'>


In [28]:
import numpy as np
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [29]:
print(type(myVector))

<class 'numpy.ndarray'>


# Stack

In [30]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

In [31]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

In [32]:
stack.pop()

'Yellow'

In [33]:
stack.isEmpty()

False

In [34]:
colors = ['Red']

In [35]:
colors.append('Green')
colors.append('Yellow')
colors.append('Blue')

In [36]:
colors

['Red', 'Green', 'Yellow', 'Blue']

# Queue

In [37]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [38]:
queue = Queue()

In [39]:
queue.enqueue('Red')

In [40]:
queue.enqueue('Green')

In [41]:
queue.enqueue('Blue')

In [42]:
queue.enqueue('Yellow')

In [43]:
print(f"Size of queue is {queue.size()}")

Size of queue is 4


In [44]:
print(queue.dequeue())

Red
